dist: xenial
language: node_js
node_js:
  - "node"

services:
  - xvfb

addons:
  apt:
    packages:
      - libgconf-2-4

install:
  # Install headless browser
  - npm install -g mocha
  - npm install -g chai
  - npm install -g nightmare
  # Install Rust
  - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=nightly -y
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustc --version
  - cargo --version

before_script:
  # Build and run Polaris server
  - git clone http://github.com/agersant/polaris
  - cd polaris
  - cargo build
  - cargo run -- -d test/db.sqlite -w .. -f  > polaris_test.log 2>&1 &
  - sleep 5
  - cd ..

script:
  - DEBUG=nightmare:*,electron:* mocha

after_failure:
  - cat polaris/polaris_test.log
