language: node_js
node_js:
  - "node"

before_install:
  # Install headless browser
  - npm install mocha
  - npm install nightmare
  # Install Rust
  - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=stable -y
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustc --version
  - cargo --version
  # Build and run Polaris server
  - git clone http://github.com/agersant/polaris
  - cd polaris
  - cargo build
  - cargo run -- -d test/db.sqlite -w .. &
  - cd ..

script:
  - sleep 15
  - npm test
