name: Build
on: push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Clone Polaris Web
      uses: actions/checkout@master
    - name: Install Node.js
      uses: actions/setup-node@v1
    - name: Clone Polaris
      run: git clone http://github.com/agersant/polaris
    - name: Store polaris version
      working-directory: polaris
      run: git rev-parse HEAD > $GITHUB_WORKSPACE/polaris-version
    - name: Retrieve cached Polaris executable
      id: cache_polaris_build
      uses: actions/cache@v1
      with:
        path: polaris/target
        key: ${{ runner.os }}-polaris-${{ hashFiles('polaris-version') }}
    - name: Install test framework
      run: |
        npm install -g jest
        npm install nightmare
    - name: Install Rust toolchain
      if: steps.cache_polaris_build.outputs.cache-hit != 'true'
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
    - name: Install libsqlite3-dev
      if: steps.cache_polaris_build.outputs.cache-hit != 'true'
      run: sudo apt-get install libsqlite3-dev
    - name: Build Polaris
      working-directory: polaris
      if: steps.cache_polaris_build.outputs.cache-hit != 'true'
      run: cargo +nightly build --release
    - name: Run Polaris
      working-directory: polaris
      run: ./target/release/polaris -d test/db.sqlite -w ..
    - name: Run Tests
      env:
        DEBUG: nightmare:*,electron:*
      run: |
        sleep 10
        xvfb-run jest --config=test/config.json
