name: Build
on: push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Clone Polaris Web
      uses: actions/checkout@master
    - name: Install Node.js
      uses: actions/setup-node@v1
    - name: Install test framework
      run: |
        npm install -g mocha
        npm install mocha-generators
        npm install chai
        npm install nightmare
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
    - name: Install libsqlite3-dev
      run: sudo apt-get install libsqlite3-dev
    - name: Clone Polaris
      run: git clone http://github.com/agersant/polaris
    - name: Store polaris version
      run: git rev-parse HEAD > /workspace/polaris-version
    - name: Retrieve cached Polaris executable
      id: cache-polaris
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-polaris-${{ hashFiles('/workspace/polaris-version') }}
    - name: Build Polaris
      working-directory: polaris
      if: steps.cache-polaris.outputs.cache-hit != 'true'
      run: cargo +nightly build --release
    - name: Run Polaris
      working-directory: polaris
      run: cargo +nightly run --release -- -d test/db.sqlite -w ..
    - name: Run Tests
      env:
        DEBUG: nightmare:*,electron:*
      run: |
        sleep 10
        xvfb-run mocha
