name: Build
on: push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install Node.js
      uses: actions/setup-node@v1
    - name: Install test framework
      run: |
        npm install mocha
        npm install chai
        npm install nightmare
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Clone Polaris
      run: git clone http://github.com/agersant/polaris
    - name: Build and Run Polaris
      uses: actions-rs/cargo@v1
      with:
        command: run
        toolchain: nightly
        args: --release --manifest-path polaris/Cargo.toml -- -d test/db.sqlite -w .
    - name: Run Tests
      env:
        DEBUG: nightmare:*,electron:*
      run: |
        sleep 5
        xvfb-run mocha
